# Book settings
title: AP CSA
author: Sonia Spindt
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

repository:
  url                       : https://github.com/SoniaSpindt/csa_textbook  # Online location of your book
  #path_to_book              : path/to/book  # Optional path to your book, relative to the repository root
  branch                    : master  # Which branch of the repository should be used when creating links (optional)


launch_buttons:
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
  thebe: true


exclude_patterns: []

execute:
  execute_notebooks: 'off'
